### ISSUE TITLE
Help in evaluation!

### ISSUE THREAD

**Issue by Sreyan88** [kuan2jiu99/audio-hallucination#1]
Thank You for the great work! We recently released [GAMA](https://sreyan88.github.io/gamaaudio/) and wanted to evaluate our model on your benchmark. Is there an evaluation script for POPE evaluation?

We have generated [this file](https://drive.google.com/file/d/1mXBD1p_qdilsTmB_xmWTEORci0Fg-InT/view?usp=sharing) for POPE - random - w/ sampling setting. The column named `output` is the output of GAMA. With our version of the evaluation script, we achieved an accuracy and F1 of 81.7 (we use string matching for evaluation). Can you please confirm if you achieved the same with your evaluation script?

Thank You again!

**Comment by kuan2jiu99** [comment]
Thank you for your interest in this work.

Using the methods proposed in our paper, the metrics obtained are as follows:

- Accuracy: 82.65%
- Precision: 85.63%
- Recall: 78.33%
- F1 Score: 81.82%
- Yes Rate: 54.26%

Our initial method involves examining the text of responses to see if they contain certain key words or phrases. If a response includes terms like "Yes" or "yes," we consider it affirmative. If it includes "No, or phrases that suggest something is missing or denied, such as "there is no sound" or "does not contain," we consider it negative. 

We consider options beyond just "yes" and "no" in our responses because some models do not follow instructions very well. To address this, we include synonyms, although we can't cover all possible variations. However, the model you proposed, GAMA, has strong capabilities in following instructions accurately, so this issue is less of a concern with it.

We will upload the evaluation-related code as soon as possible.

**Comment by Sreyan88** [comment]
Thank You so much! It is really helpful, and it is also exciting to see GAMA perform so well!

Thank You again for the great work!

Best,
Sreyan
